name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']

    services:
      database:
        image: mysql:latest
        env:
          MYSQL_DATABASE: wordpress_tests
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-polyfills:1.1

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Setup tests
        run: bash bin/install-wp-tests.sh wordpress_tests root root 127.0.0.1 latest true

      - name: Execute tests
        run: composer test
